POST http://localhost:3001/api/users
Content-Type: application/json
{
    "username": "root",
    "name": "Superuser",
    "password": "salainen"
}


### 
GET http://localhost:3001/api/users

### 
GET http://localhost:3001/api/notes

### 
POST http://localhost:3001/api/notes
Content-Type: application/json

{
    "content": "Test again",
    "important": true,
    "userId": "647a350d15740c9210bb0464"
}